version: '3.9'
services:
  text-generation-webui:
    container_name: text-generation-webui
    restart: unless-stopped
    volumes:
      - '${MODEL_DIR}:/models'
      - '${EXTENSIONS_DIR}:/extensions'
      - '${CHARACTERS_DIR}:/characters'
      - '${SETTINGS_DIR}:/settings'
      - '${LOGS_DIR}:/logs'
      - '${LORAS_DIR}:/loras'
      - '${DATASETS_DIR}:/datasets'
      - '${PRESETS_DIR}:/presets'
    ports:
      - '7860:7860'
      - '5000:5000'
    image: 'noneabove1182/text-gen-ui-gpu:latest'
    environment:
      - OPENEDAI_EMBEDDING_DEVICE=cuda
    ulimits:
      memlock: -1
    mem_limit: 50gb
    shm_size: '4gb'
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command:
      [
        "--model",
        "${MODEL}",
        "--listen",
        "--listen-port",
        "7860",
        "--listen-host",
        "0.0.0.0",
        "--api",
        "--verbose",
        "--settings",
        "/settings/settings.yaml"
      ]
