version: '3.9'
services:
  text-generation-webui:
    container_name: text-generation-webui
    restart: always
    volumes:
      - '${MODEL_DIR}:/models'
      - '${EXTENSIONS_DIR}:/extensions'
      - '${CHARACTERS_DIR}:/characters'
      - '${SETTINGS_DIR}:/settings'
    ports:
      - '7860:7860'
      - '5000:5000'
      - '5001:5001'
    image: 'noneabove1182/text-gen-ui-gpu:latest'
    ulimits:
      memlock: -1
    mem_limit: 50gb
    shm_size: '4gb'
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]
    command:
      [
        "--model",
        "${MODEL}",
        "--loader",
        "exllama_hf",
        "--listen",
        "--listen-port",
        "7860",
        "--api",
        "--api-blocking-port",
        "5000",
        "--extensions",
        "openai",
        "--verbose",
        "--settings",
        "/settings/settings.yaml"
      ]
